### PR TITLE
Fix clippy warnings

### PR DESCRIPTION
**Pull request by joseluis**
This PR aims to fix around 60 warnings and 16 errors reported by [clippy](https://github.com/rust-lang/rust-clippy)

### CODE REVIEW

**Comment by joseluis** [comment]
the following clippy errors are funny:

```rust
error: using `clone` on a double-reference; this will copy the reference of type `&[u8]` instead of cloning the inner type
  --> src/keypair/private_key.rs:50:42
50 |                 Sha256r::default().chain(preimage.clone()),
   |                                          ^^^^^^^^^^^^^^^^
   |
   = note: `#[deny(clippy::clone_double_ref)]` on by default
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#clone_double_ref
help: try dereferencing it
   |
50 |                 Sha256r::default().chain(&(*preimage).clone()),
   |                                          ^^^^^^^^^^^^^^^^^^^^
help: or try being explicit if you are sure, that you want to clone a reference
   |
50 |                 Sha256r::default().chain(<&[u8]>::clone(preimage)),
   |                                          ^^^^^^^^^^^^^^^^^^^^^^^^

error: using `clone` on a double-reference; this will copy the reference of type `&[u8]` instead of cloning the inner type
  --> src/keypair/private_key.rs:55:58
   |
55 |                 Sha256r::default().chain(Sha256r::digest(preimage.clone())),
   |                                                          ^^^^^^^^^^^^^^^^
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#clone_double_ref
help: try dereferencing it
   |
55 |                 Sha256r::default().chain(Sha256r::digest(&(*preimage).clone())),
   |                                                          ^^^^^^^^^^^^^^^^^^^^
help: or try being explicit if you are sure, that you want to clone a reference
   |
55 |                 Sha256r::default().chain(Sha256r::digest(<&[u8]>::clone(preimage))),
   |                                                          ^^^^^^^^^^^^^^^^^^^^^^^^

error: using `clone` on a double-reference; this will copy the reference of type `&[u8]` instead of cloning the inner type
  --> src/encryption/mod.rs:67:25
   |
67 |         let data = &mut message.clone().to_vec();
   |                         ^^^^^^^^^^^^^^^
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#clone_double_ref
help: try dereferencing it
   |
67 |         let data = &mut &(*message).clone().to_vec();
   |                         ^^^^^^^^^^^^^^^^^^^
help: or try being explicit if you are sure, that you want to clone a reference
   |
67 |         let data = &mut <&[u8]>::clone(message).to_vec();
   |                         ^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to 3 previous errors
```

In this case the clippy advices don't really work. But I suspect that the clone is unnecessary, since those are immutable references to a slice, so I've opted to remove the cloning, but you should definitely [review that commit](https://github.com/Firaenix/bsv-wasm/pull/18/commits/e2e62b1cb084f49c47fbb410e090af99eabfb532). At least all the tests seem to pass.

**Comment by joseluis** [comment]
After this is merged I can add clippy to the github actions after the rustfmt check

**Comment by Firaenix** [comment]
Ahh yeah thats weird, ok I'll dig a bit deeper, thanks for the heads up

**Comment by joseluis** [comment]
there were also a bunch of simply unneeded clones on copy types that clippy warned about. This case feels similar but I think the linter gets confused because it can't be sure of the intention behind...

**Comment by Firaenix** [comment]
There have been many changes since this PR was open, I will fix up most of these and make a new PR, thanks for bringing it to my attention :)

**Pull request closed without merging**
