### PR TITLE
make sure to format the rust code

### LINKED ISSUE #9: format the source code using rustfmt
In order to ensure a consistent style with the rest of the Rust ecosystem, and it would also make it easier to collaborate.

Running `rustfmt` will change the indentation from 2 spaces to 4, make sure there's a newline at the end of each file, reorder import lines alphabetically, ensure the maximum line length... etc.

https://github.com/rust-dev-tools/fmt-rfcs/blob/master/guide/guide.md

### PR DESCRIPTION
**Pull request by joseluis**
Fixes #9 

I've updated this PR with all the related stuff:

- [x] synced with the latest master branch.
- [x] formatted the source & test files.
- [x] add a github action to check the format.
- [x] add pre-commit hook

### CODE REVIEW

**Comment by Firaenix** [comment]
Great idea, is it possible to get this in some sort of git commit hook?

**Comment by joseluis** [comment]
> Great idea, is it possible to get this in some sort of git commit hook?

Yes, I think it's possible. I'm gonna try to create a new PR to add that functionality

**Comment by joseluis** [comment]
BTW it would be probably be simpler to close this PR and you just rustfmt over your last changes...

**Comment by joseluis** [comment]
> > Great idea, is it possible to get this in some sort of git commit hook?
> 
> Yes, I think it's possible. I'm gonna try to create a new PR to add that functionality

done in #15

**Comment by joseluis** [comment]
in order to configure git locally to use the new hook:

```sh
git config core.hooksPath "./.git_hooks"
```

**Comment by joseluis** [comment]
After merging the current PR, there are also many Clippy warnings and errors that should be fixed too...

**Comment by Firaenix** [comment]
PR looks good, most of the warnings come from seemingly unused imports in build targets that aren't wasm32. There's probably a setting we can flick to turn those off, but that can be in a separate PR.

**Comment by joseluis** [comment]
> PR looks good, most of the warnings come from seemingly unused imports in build targets that aren't wasm32. There's probably a setting we can flick to turn those off, but that can be in a separate PR.

opened #17

**Pull request merged**
