### PR TITLE
Fix #66 `reverse_k` signature digest

### LINKED ISSUE #66: `ECDSA::sign_with_deterministic_k_impl` produces wrong `(r, s)`
The `reverse_k` flag only changes the byte order of the `k_digest` but not the `msg_scalar` even though they're the same digest.

```rust
let private_key = PrivateKey::from_wif("KzmbmFNo39aF85nxV24MqK3JCat3TYNUVJVaQdzgdSHLwuPFFyMt").unwrap();
let preimage = hex::decode("010000008c8dfd409fbe3bd76c6c074086b89b56e18c31899da98ccd7b05baf769a096ae3bb13029ce7b1f559ef5e747fcac439f1455a2ec7c5f09b72290795e7066504442c4eb085fdcf6c06faed60e1cbfcc852bb04801c70d5b499f122171b14f61af000000001976a914cdc1c584ca737579b470ab4407220d67a294774488ac4086010000000000ffffffff7bc9a0bf72f4ab98d03bd5b1f309976d9f2d30ff8e2c64ad2b3a13456015654b0000000041000000").unwrap();
let sig = ECDSA::sign_with_deterministic_k(&private_key, &preimage, bsv::SigningHash::Sha256d, true).unwrap();
// r - 00b2327c56ced7cf78414c0115e3642525899bba85cc3f63a0fe23ff9c8f1b858b
// s - 5bd5fb8f4147387269503637b43de3620a735665906831a238a9a021de8914b8
```

If we sign the same hashbuf in [bsv.js](https://github.com/moneybutton/bsv/tree/bsv-legacy) our r-values match but the s-values don’t. 

```js
const privkey =  bsv.PrivateKey.fromWIF("KzmbmFNo39aF85nxV24MqK3JCat3TYNUVJVaQdzgdSHLwuPFFyMt");
const sighashType = bsv.crypto.Signature.SIGHASH_ALL | bsv.crypto.Signature.SIGHASH_FORKID;
const hashbuf = Buffer.from('17cac225a81ac668a63a330b0ad3c7218b94e11f466b44405debd2d572290605', 'hex');
// 'little' to match bsv.Transaction.sighash.sign
const sig = bsv.crypto.ECDSA.sign(hashbuf, privkey, 'little').set({ nhashtype: sighashType });
// r - 00b2327c56ced7cf78414c0115e3642525899bba85cc3f63a0fe23ff9c8f1b858b
// s - 676d53f10b4c8412864d896c07e2c2187203b988904a28a7e7facd96eeccba0e
```

This makes sense because we only used the `k_digest` to calculate `r` (k * G). But the signature proof relies on `k`, `r` & the `msg_scalar`

Since the `msg_scalar` is backwards we get a totally different value for `s` than what we should expect.

### Fix

We should update  [this line](https://github.com/Firaenix/bsv-wasm/blob/master/src/ecdsa/sign.rs#L35) to reverse the `msg_scalar` whenever we reverse the `k_digest` 

```rust
let msg_scalar = match reverse_endian_k {
  true => <Scalar as Reduce<U256>>::from_le_bytes_reduced(final_digest),
  false => <Scalar as Reduce<U256>>::from_be_bytes_reduced(final_digest),
};
```

This enables us to generate signatures that are fully backwards compatible with bsv.js & allows us to verify signatures from either library

```rust
let sig_le = ECDSA::sign_with_deterministic_k(&private_key, &preimage, bsv::SigningHash::Sha256d, true).unwrap();
// r - 00b2327c56ced7cf78414c0115e3642525899bba85cc3f63a0fe23ff9c8f1b858b
// s - 676d53f10b4c8412864d896c07e2c2187203b988904a28a7e7facd96eeccba0e

let sig_be = ECDSA::sign_with_deterministic_k(&private_key, &preimage, bsv::SigningHash::Sha256d, false).unwrap();
// r - 00f81e04ae4e1be88c9eca52679e397c15cf40dd3678ff2328ef513af406edff38 
// s - 1bc7116d947e934b375c6af4b90c2c029b9bf4a9dfcb3e3a28ed2723cd51b0cf
```

```js
let sig_le = bsv.crypto.ECDSA.sign(hashbuf, privkey, 'little').set({ nhashtype: sighashType });
// r - 00b2327c56ced7cf78414c0115e3642525899bba85cc3f63a0fe23ff9c8f1b858b
// s - 676d53f10b4c8412864d896c07e2c2187203b988904a28a7e7facd96eeccba0e

// endian flag set to 'big' or undefined 
let sig_be = bsv.crypto.ECDSA.sign(hashbuf, privkey).set({ nhashtype: sighashType });
// r - 00f81e04ae4e1be88c9eca52679e397c15cf40dd3678ff2328ef513af406edff38 
// s - 1bc7116d947e934b375c6af4b90c2c029b9bf4a9dfcb3e3a28ed2723cd51b0cf
```

My main concern here is backwards compatibility. Since `reverse_k` is baked into `Transaction::sign_impl`, this affects all transactions signed using `tx.sign`

I will submit a PR for this shortly

### PR DESCRIPTION
**Pull request by blocksurf**
- Adds `DigestAction` enum to handle the byte order of the `k_digest` and `msg_scalar` during ECDSA sign/verify
- `SighashSignature::from_der_impl` now checks the sig length before attempting to remove the sighash byte
- `checksig` and `multisig` will verify the reverse digest if `verify_tx_signature` fails the first time. This guarantees that the interpreter can validate signatures regardless of the byte order used for the digest

### CODE REVIEW

**Comment by blocksurf** [comment]
The most recent commit adds `reverse_k` flags where necessary. It also updates the signatures in `tests/sighash.rs`

All of the tests pass again but there are still two outstanding issues

### Signature verification

Signatures produced with a reversed digest still can't be verified by their signer because the function called by `ECDSA::verify_digest_impl` [here](https://github.com/Firaenix/bsv-wasm/blob/master/src/ecdsa/verify.rs#L13) assumes our scalars will always be [big endian](https://github.com/RustCrypto/signatures/blob/d1c87138a47f6c3819c5df99a722a5e03ec33297/ecdsa/src/verify.rs#L89)

### Interpreter

The multisig tests in `tests/interpreter_signatures.rs` failed unless I switched the order of the private keys. I'm not sure what broke. Still debugging this

**Comment by blocksurf** [comment]
Fixed the outstanding issues in `ecdsa/verify.rs` & `interpreter/script_matching.rs`

Changes:

- Removed `msg_digest` from `ECDSA::sign_preimage_deterministic_k` since its identical to `k_digest`

- `SighashSignature::from_der_impl` checks sig length before attempting to remove sighash byte

- `checksig` and `multisig` will automatically check the reverse digest if `verify_tx_signature` fails the first time. This guarantees that the interpreter will work properly even if it doesn't know the byte order of the original digest

**Comment by blocksurf** [comment]
> I do like this PR, while I do have some concerns about the changes to the API for backwards compatibility's sake, I dont mind adding another flag to the already low level ECDSA functions.


Totally agree this should all be opt-in. I added a `DigestAction` enum for the underlying impls and restored most of the functions back to their current form

These two function will still need flags though since their impls are `pub(crate)`

- `Transaction::sign`
- `ECDSA::verify_digest`

I went ahead & implemented them as you suggested

>if you pass None to the function call, it acts as it does currently


### `ECDSA::verify_digest`

`reverse_digest: Option<bool>`

Default value for `None`:

```rust
reverse_digest.unwrap_or(false)
```


### `Transaction::sign`

`digest_action: Option<DigestAction>`

Default value for `None`:

```rust
digest_action.unwrap_or(DigestAction::ReverseK)
```

But if you want to avoid making changes to the existing function signatures we could do this instead:

- Create a separate `Transaction::sign_legacy` method that accepts `Option<DigestAction>`
- Make `ECDSA::verify_digest_impl` public

What do you think?

**Comment by Firaenix** [comment]
Hmm that's an interesting option to add new functions. If we do go that route, I do have a request that kind of adds some scope but @deanmlittle brought up with me during some quick discussions.

He mentioned instead of the library reversing anything, you should be passing digests in already formatted how you need them to be. Do you think it would be worth adding a new function to handle that case?

@deanmlittle did I explain what you had in mind accurately enough?

**Comment by blocksurf** [comment]
I like the idea of handling digests outside the library. Would you like to keep the existing functions unchanged & add new functions that accept the digest directly?

How would we handle functions that call `pub(crate)` methods internally? `Transaction::sign` needs to generate the preimage before signing, the return type `SighashSignature` has private fields, etc. 

As for the digests I think a good option would be to implement them as an associated trait type of vecs & slices. Something like this

```rust
pub trait ToDigest {
    type HashDigest: digest::FixedOutput<OutputSize = digest::consts::U32>
		+ digest::BlockInput
		+ Clone
		+ Default
		+ digest::Reset
		+ digest::Update
		+ FixedOutput
		+ ReversibleDigest;

    fn to_digest(&self, hash_algo: SigningHash, reverse: bool) -> Self::HashDigest;
}

impl<T> ToDigest for T
where
    T: AsRef<[u8]>,
{
    type HashDigest = Sha256r;

    fn to_digest(&self, hash_algo: SigningHash, reverse: bool) -> Self::HashDigest {
        let d = match hash_algo {
            SigningHash::Sha256 => Digest::chain(Self::HashDigest::default(), self.as_ref()),
            SigningHash::Sha256d => Digest::chain(Self::HashDigest::default(), Self::HashDigest::digest(self.as_ref())),
        };

        match reverse {
            true => d.reverse(),
            false => d,
        }
    }
}
```

Then you could just go

```rust
let message = b"Hello";
let digest = message.to_digest(SigningHash::Sha256d, true);
```

**Comment by Firaenix** [comment]
I do really like your trait idea. Not sure how that would work in Javascript but worth playing around with.

I think lets go with a fresh function call for externally created digests, we can figure out what to do with the other functions later based on usage. 


Thanks again for your input!

**Pull request merged**
